### ISSUE TITLE
comments should add trailing whitespace

### ISSUE THREAD

**Issue by chadams** [vidalab/meteor-html2jade#1]
// inject:partials

becomes
    

when it should become
    

I know it's kind of nit picky, but a lot of injectors cannot find the comments unless you add a space at the end. 

What do you think?

**Comment by sangd** [comment]
That looks like jade to html, and I think this app only does html to jade. I'm not sure how that got converted. Besides, the app is using html2jade package which does this conversion mostly (exception for some meteor js tags). You can have a look at the package here:
https://github.com/donpark/html2jade
