### ISSUE TITLE
encode chinese into 

### ISSUE THREAD

**Issue by fuchao2012** [vidalab/meteor-html2jade#4]
## html code

```
<p>this is test </p>
 <p>这是中文</p>
```
## jade code

```
p this is test 
p &#36825;&#26159;&#20013;&#25991;
```

**Comment by Grawl** [comment]
Same with any non-ASCII glyphs. Using [html2jade.org](http://html2jade.org) instead.

**Comment by dnprock** [comment]
Just updated our packages to fix the issue. Please try again.
![screen shot 2017-03-08 at 11 24 00 am](https://cloud.githubusercontent.com/assets/497205/23719892/d6feffd8-03f1-11e7-9f78-3adc72d5efad.png)

**Comment by Grawl** [comment]
Cool!
